// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// defaultSections defines the section IDs, titles, icons, and colors
// so placeholder divs are rendered on initial page load for SSE patching.
var defaultSections = []ChartSection{
	{ID: "section-system", Title: "System", Icon: "\u2699", Color: "#06b6d4"},
	{ID: "section-runtime", Title: "Runtime", Icon: "\u25b6", Color: "#339970"},
	{ID: "section-http", Title: "HTTP", Icon: "\u21c4", Color: "#3b82f6"},
	{ID: "section-nats", Title: "NATS", Icon: "\u26a1", Color: "#8b5cf6"},
	{ID: "section-jetstream", Title: "JetStream", Icon: "\u2601", Color: "#f59e0b"},
}

func MetricsDashboard(sections []ChartSection, streams []StreamDetail, consumers []ConsumerDetail, connections []ConnectionDetail) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"metrics-dashboard\" class=\"metrics-dashboard\" data-signals='{\"_isConnected\": false, \"timestamp\": \"--:--:--\"}' data-init=\"@get('/api/metrics/sse')\"><div class=\"dashboard-header\"><h2>System Metrics</h2><div class=\"status-bar\"><span class=\"connection-status\" data-show=\"$_isConnected\"><span class=\"status-dot connected\"></span> Connected</span> <span class=\"connection-status\" data-show=\"!$_isConnected\"><span class=\"status-dot disconnected\"></span> Connecting...</span> <span class=\"timestamp\" data-text=\"$timestamp\"></span></div></div><div class=\"sections-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(sections) > 0 {
			for _, section := range sections {
				templ_7745c5c3_Err = Section(section).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		} else {
			for _, placeholder := range defaultSections {
				templ_7745c5c3_Err = Section(placeholder).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"details-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = StreamsTable(streams).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ConsumersTable(consumers).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ConnectionsTable(connections).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div class=\"metrics-footer\"><span class=\"timestamp\">Last updated: <span data-text=\"$timestamp\"></span></span> <a href=\"/metrics\" target=\"_blank\" class=\"prometheus-link\">View Raw Prometheus Metrics</a></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
